controller_list:
  - name: fake_robot_arm_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - J0
      - J1
      - J2
initial:  # Define initial robot poses per group
  - group: robot_arm_hand
    pose: home